sources:
  - UbuntuMono.designspace
  - UbuntuMono-Italic.designspace
axisOrder:
  - wght
  - ital
familyName: Ubuntu Mono
buildStatic: false
buildWebfont: false
stat:
  Ubuntu[wdth,wght].ttf:
      - name: Width
        tag: wdth
        values:
          - name: Condensed
            value: 75
          - name: Normal
            value: 100
            flags: 2
      - name: Weight
        tag: wght
        values:
          - name: Thin
            value: 100
          - name: Light
            value: 300
          - name: Regular
            value: 400
            linkedValue: 700
            flags: 2
          - name: Medium
            value: 500
          - name: Bold
            value: 700
          - name: Extra Bold
            value: 800
      - name: Italic
        tag: ital
        values:
        - name: Roman
          value: 0
          linkedValue: 1
          flags: 2
  Ubuntu-Italic[wdth,wght].ttf:
      - name: Width
        tag: wdth
        values:
          - name: Condensed
            value: 75
          - name: Normal
            value: 100
            flags: 2
      - name: Weight
        tag: wght
        values:
          - name: Thin
            value: 100
          - name: Light
            value: 300
          - name: Regular
            value: 400
            linkedValue: 700
            flags: 2
          - name: Medium
            value: 500
          - name: Bold
            value: 700
          - name: Extra Bold
            value: 800
      - name: Italic
        tag: ital
        values:
        - name: Italic
          value: 1