sources:
  - UbuntuMono.designspace
  - UbuntuMono-Italic.designspace
axisOrder:
  - wght
  - ital
familyName: Ubuntu Mono
buildStatic: false
buildWebfont: false
stat:
  UbuntuMono[wght].ttf:
    - name: Weight
      tag: wght
      values:
        - name: Thin
          value: 100
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: Bold
          value: 700
    - name: Italic
      tag: ital
      values:
      - name: Roman
        value: 0
        linkedValue: 1
        flags: 2
  UbuntuMono-Italic[wght].ttf:
    - name: Weight
      tag: wght
      values:
        - name: Regular
          value: 400
          linkedValue: 700
        - name: Medium
          value: 500
        - name: Bold
          value: 700
    - name: Italic
      tag: ital
      values:
      - name: Roman
        value: 1